/*
 *
 * ReservationsPropainerOne constants
 *
 */

export const CHANGE_RESERVATIONSPASSED =
  'app/ReservationsPage/CHANGE_RESERVATIONSPASSED';
export const CHANGE_RESERVATIONSUPCOMING =
  'app/ReservationsPage/CHANGE_RESERVATIONSUPCOMING';
export const CHANGE_RESERVATIONSNEW =
  'app/ReservationsPage/CHANGE_RESERVATIONSNEW';
export const CHANGE_RESERVATIONSFILTER1 =
  'app/ReservationsPage/CHANGE_RESERVATIONSFILTER1';
export const CHANGE_RESERVATIONSFILTER2 =
  'app/ReservationsPage/CHANGE_RESERVATIONSFILTER2';
export const CHANGE_RESERVATIONSFILTER3 =
  'app/ReservationsPage/CHANGE_RESERVATIONSFILTER3';
export const CHANGE_RESERVATIONSFILTER4 =
  'app/ReservationsPage/CHANGE_RESERVATIONSFILTER4';
export const CHANGE_GETRESERVATIONSRESULT =
  'app/ReservationsPage/CHANGE_GETRESERVATIONSRESULT';
export const CHANGE_GETRESERVATIONSERROR =
  'app/ReservationsPage/CHANGE_GETRESERVATIONSERROR';
export const CHANGE_GETRESERVATIONSSUBMITTING =
  'app/ReservationsPage/CHANGE_GETRESERVATIONSSUBMITTING';
export const CHANGE_ACCEPTBOOKINGRESULT =
  'app/ReservationsPage/CHANGE_ACCEPTBOOKINGRESULT';
export const CHANGE_ACCEPTBOOKINGERROR =
  'app/ReservationsPage/CHANGE_ACCEPTBOOKINGERROR';
export const CHANGE_ACCEPTBOOKINGSUBMITTING =
  'app/ReservationsPage/CHANGE_ACCEPTBOOKINGSUBMITTING';
export const CHANGE_ACCEPTAUTOBOOKINGRESULT =
  'app/ReservationsPage/CHANGE_ACCEPTAUTOBOOKINGRESULT';
export const CHANGE_ACCEPTAUTOBOOKINGERROR =
  'app/ReservationsPage/CHANGE_ACCEPTAUTOBOOKINGERROR';
export const CHANGE_ACCEPTAUTOBOOKINGSUBMITTING =
  'app/ReservationsPage/CHANGE_ACCEPTAUTOBOOKINGSUBMITTING';
  export const CHANGE_ACCEPTAUTOOFFBOOKINGRESULT =
  'app/ReservationsPage/CHANGE_ACCEPTAUTOOFFBOOKINGRESULT';
export const CHANGE_ACCEPTAUTOOFFBOOKINGERROR =
  'app/ReservationsPage/CHANGE_ACCEPTAUTOOFFBOOKINGERROR';
export const CHANGE_ACCEPTAUTOOFFBOOKINGSUBMITTING =
  'app/ReservationsPage/CHANGE_ACCEPTAUTOOFFBOOKINGSUBMITTING';
export const CHANGE_DECLINEBOOKINGRESULT =
  'app/ReservationsPage/CHANGE_DECLINEBOOKINGRESULT';
export const CHANGE_DECLINEBOOKINGERROR =
  'app/ReservationsPage/CHANGE_DECLINEBOOKINGERROR';
export const CHANGE_DECLINEBOOKINGSUBMITTING =
  'app/ReservationsPage/CHANGE_DECLINEBOOKINGSUBMITTING';
export const ACCEPTBOOKING = 'app/ReservationsPage/ACCEPTBOOKING';
export const ACCEPTAUTOBOOKING = 'app/ReservationsPage/ACCEPTAUTOBOOKING';
export const ACCEPTAUTOOFFBOOKING = 'app/ReservationsPage/ACCEPTAUTOOFFBOOKING';
export const DECLINEBOOKING = 'app/ReservationsPage/DECLINEBOOKING';
export const GETRESERVATIONSSUBMIT =
  'app/ReservationsPage/GETRESERVATIONSSUBMIT';
export const GETRESERVATIONSPROCESS =
  'app/ReservationsPage/GETRESERVATIONSPROCESS';
export const SWITCHUPCOMING = 'app/ReservationsPage/SWITCHUPCOMING';
export const SWITCHPASSED = 'app/ReservationsPage/SWITCHPASSED';
export const SWITCHNEW = 'app/ReservationsPage/SWITCHNEW';
export const SWITCHFILTER1 = 'app/ReservationsPage/SWITCHFILTER1';
export const SWITCHFILTER2 = 'app/ReservationsPage/SWITCHFILTER2';
export const SWITCHFILTER3 = 'app/ReservationsPage/SWITCHFILTER3';
export const SWITCHFILTER4 = 'app/ReservationsPage/SWITCHFILTER4';
