export const RESTART_ON_REMOUNT = '@@saga-injector/restart-on-remount';
export const DAEMON = '@@saga-injector/daemon';
export const ONCE_TILL_UNMOUNT = '@@saga-injector/once-till-unmount';
export const GUESTS_ARRAY = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
export const BED_ARRAY = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10];
export const graphqlDevEndpoint = 'http://localhost:4000';
export const graphqlProdEndpoint = 'https://graphql.beddertravel.com';
export const backendDevEndpoint = 'http://localhost:8000/app.php/api/v1';
export const backendProdEndpoint = 'https://api.beddertravel.com/app.php/api/v1';