/*
 *
 * SignUpPropainer constants
 *
 */

export const CHANGE_FACEBOOKSUBMITTING =
  'app/SignUpPage/CHANGE_FACEBOOKSUBMITTING';
export const CHANGE_FACEBOOKRESULT = 'app/SignUpPage/CHANGE_FACEBOOKRESULT';
export const CHANGE_FACEBOOKERROR = 'app/SignUpPage/CHANGE_FACEBOOKERROR';
export const CHANGE_FACEBOOKOAUTHRESULT =
  'app/SignUpPage/CHANGE_FACEBOOKOAUTHRESULT';
export const SUBMITFACEBOOK = 'app/SignUpPage/SUBMITFACEBOOK';
export const SUCCESSFACEBOOK = 'app/SignUpPage/SUCCESSFACEBOOK';
